### ISSUE TITLE
MQTT Настройка границ влажности (левая граница)

### ISSUE THREAD

**Issue by maxmarvil** [Rightech/test-alpha#1]
![image](https://user-images.githubusercontent.com/7899443/57285641-51337480-70bc-11e9-8fc0-0d523923cf8d.png)

При указании цвета 2го сегмента поменялся цвет у последующих до граници 50%

по правую сторону такого не наблюдается

**Comment by maxmarvil** [comment]
Заметил - с права на лева заполнение от границы работает (настройка правой границы)
С лева на право начинает прыгать - как будто пытается заполнить до правой границы пропуская области орниченые метками значений.

Калькуляция меток отдельный вопрос.

**Comment by prohazko2** [comment]
![ric_levels](https://user-images.githubusercontent.com/40128245/57298678-771c4180-70db-11e9-9dce-4a459f46da86.png)

Да, у этого контрола примерно такая логика:
- для значений, который выходят за диапазон цветовая индикация задаётся явно (зелёные стрелки)
- индикация для диапазонов между уровнями задаётся слева направо (красные стрелки)

Т.е. для: 
- промежутка от 0 до 50 берётся светло-синий
- промежутка от 50 до 100 берётся тёмно синий

**Comment by prohazko2** [comment]
Между этими диапазонами можно задать дополнительные уровни через :heavy_plus_sign: 
Цветовая индикация для них так же пойдёт слева направо (по возрастанию)

![Screenshot from 2019-05-07 15-29-11](https://user-images.githubusercontent.com/40128245/57299371-083fe800-70dd-11e9-9a74-f37fd98b8631.png)

**Comment by prohazko2** [comment]
Изначально UI был более простым/понятным, но со временем усложнился.
Над этим стоит поработать, согласен

**Comment by maxmarvil** [comment]
После работы опишу issue с мыслями по контролу. может полезными будут
По последовательности понял как работает.

**Comment by maxmarvil** [comment]
Закрываю. Продолжение следует.

**Comment by prohazko2** [comment]
:+1: спасибо!
