### ISSUE TITLE
Переименование нового автомата

### ISSUE THREAD

**Issue by maxmarvil** [Rightech/test-alpha#11]
![image](https://user-images.githubusercontent.com/7899443/57574071-d612eb00-743a-11e9-9046-d9beec0ab5a9.png)

1 переименовал изначальное состояние
2 попробовал сохранить
жму о'кей
![image](https://user-images.githubusercontent.com/7899443/57574094-2a1dcf80-743b-11e9-893f-9f1fb0ce164b.png)

 Поп-ап сворачивается, курсор на заголовке мигает. Не могу перейти к редактированию описания. НО новый заголовок всё же сохранился (после перезагрузки страницы увидел).

**Comment by prohazko2** [comment]
Исправили в  `1.8.0`
