### ISSUE TITLE
Редактирование перехода в автомате + заметка

### ISSUE THREAD

**Issue by maxmarvil** [Rightech/test-alpha#12]
![image](https://user-images.githubusercontent.com/7899443/57574175-baa8df80-743c-11e9-98b9-394a746405bb.png)

Здесь два момента.
1. Наглядный.. при добавлении условия вываливается поп-ап, не живой. 
Полагаю должен быть конструктор условий из параметров и инструментов ... но нет...
2. Заметка: Мне было не очевидно что получение данных находится в регистрации. Под регистрацией я понимал бы событие появления устройства(объекта) в сети (статус ON), Работа с api-соцсетей(вошёл в ВК -> запуск таймера на включение шредера с заправленным паспортом), регистрация переходных состояний(к примеру тех же геозон) 
В свою очередь получение данных лучше бы смотрелось в "Параметры" или "Данные" 

Простои получения данных ещё хорошо бы нагляднее сделать. Мол если сработал датчик дыма, активен 10 мин а после этого тишина (устройство OFF), то дело пахнет киросином

**Comment by prohazko2** [comment]
1. Верно, прямо сейчас исправляем
2. Согласен, думаем вынести эти события на верхний уровень, в более видное место. Так как они чаще всего используются

**Comment by prohazko2** [comment]
> Мол если сработал датчик дыма, активен 10 мин а после этого тишина

Подобный сценарий можно реализовать при помощи запуска таймера

![Screenshot from 2019-05-14 18-15-22](https://user-images.githubusercontent.com/40128245/57709773-4a849e80-7674-11e9-8893-4ddf20229ed4.png)

**Comment by maxmarvil** [comment]
Вопрос по состояниям. Действие на входе и Действие на выходе. 
Как понимаю - для первого это событие входа в состояние , к примеру на старте автомата выключить лампочку и обогреватель - типа их дефолтное состояние.
При выходе из состояния - это действия при смене текущего состояния на какое то другое . 
К примеру отправить письмо или сделать запрос или пушнуть сообщение по mqtt.

отработает зацикливание состояния полностью? ведь по факту смены состояния нет.
Лишь формальное. В таком случае отработает действие на выходе?

**Comment by prohazko2** [comment]
На примере выше переходы:
- `t1` - `init` - происходит сразу после запуска автомата
- `t2` - происходит каждый раз, когда объект присылает данные
- `t3` - происходит при срабатывании таймера

![nodata](https://user-images.githubusercontent.com/40128245/58752605-a051a700-84ba-11e9-8cd0-75797387e506.png)

Так при запуске автомата :
 - он сразу переходит в состояние `s1` 
 - при входе в состояние `s1` запускается `таймер#1` на 10мин
 - автомат находится в состоянии `s1` пока не произойдёт одно из 2-ух событий:  

1. Получены данные
2. Сработал  `таймер#1`

При возникновении события `1. Получены данные` (устройство отправило пакет с данными) - переход `t2` всё же осуществляется, в то же самое `s1`:
 - при выходе из `s1` выполняется  действие - остановить `таймер#1`
 - (сразу) при входе в `s1`  выполняется действие - запустить `таймер#1` (снова на 10мин)

Т.е. происходит сброс таймера каждый раз, когда устройство отправляет данные.

При возникновении события `2. Сработал  таймер#1` (устройство уже 10мин молчит) - автомат переходит из `s1` в `s2` по переходу `t3`. 

При входе в  `s2` уже можно задать разные действия:
 - вывести сообщение в интерфейс
 - отправить команду другому устройству
 - отправить E-mail или SMS
 - отправить HTTP запрос куда-нибудь
 - выполнить собственный обработчик на JS
 - ... ещё что-нибудь о чём я забыл

**Comment by prohazko2** [comment]
Помимо этого в платформе есть отдельные события:
 - устройство ушло в `offline`
 - устройство вышло в `online`  

которые генерируются при разрыве и восстановлении TCP-соединения.

Но мы их пока не добавляли в базовую модель, т.к. ещё тестируем

**Comment by ferguster** [comment]
Обновили интерфейс. Добавили новый редактор условий. Большое спасибо вам спасибо!

**Comment by prohazko2** [comment]
Сейчас выглядит так:
![image](https://user-images.githubusercontent.com/40128245/59939170-bfab7680-945f-11e9-90d4-a003c260726d.png)

Можно кодом:
![image](https://user-images.githubusercontent.com/40128245/59939204-d8b42780-945f-11e9-83f0-f0c2183ba29e.png)
