### ISSUE TITLE
Графики значений параметров независимы и недвижимы

### ISSUE THREAD

**Issue by maxmarvil** [Rightech/test-alpha#13]
![Снимок экрана](https://user-images.githubusercontent.com/7899443/57756199-6e3ef780-76fb-11e9-94b4-cc62fae95258.png)
Собственно неприятность по ощущениям заключается в сочетании независимости и недвижимости. 

Для графика динамично обновляющихся данных допустимо то что он может быть поверх всего, в целях мониторинга значений, но для такого кейса важна возможность перемещать окошко графика и изменять его размеры. Мысли по этому поводу в отдельном issue изложу

**Comment by prohazko2** [comment]
Тут скорее баг чем фича, т.к. существование этих графиков не подразумевалось за пределами журнала объекта. И по хорошему должны закрываться при переходе на другую вкладку.

**Comment by prohazko2** [comment]
Но теперь я думаю, что такой вариант работы с плавающим виджетом может оказаться удобным

**Comment by maxmarvil** [comment]
В соседнем issue чуть описал вариант использование фичебага (кнопки режимов открытия), Эта бага из тех - если приодеть и оснастить то уже фича )
Заметил, что множественное открытие графиков пофиксили.

**Comment by slavian57** [comment]
Задача принята в работу
