### ISSUE TITLE
Заметка, предложение: Функционал боксов параметров

### ISSUE THREAD

**Issue by maxmarvil** [Rightech/test-alpha#14]
![image](https://user-images.githubusercontent.com/7899443/57784011-d7dcf700-7737-11e9-89c4-07b4eb7550b4.png)
Бокс вывода параметра кликабельный, но не на все 100%, значение не входит в кликабельный объект бокса. с одной стороны даёт возможность скопировать значения без клика, с другой - желая посмотреть статистику по данному параметру хочется кликнуть по самому выделяющемуся объекту в боксе - а это как раз значение.

Кстати - на этих боксах нет обозначений что откроется статистика.

Сбствено предложение:
В боксе в правом нижнем углу добавить две небольшие кнопочки(иконочные) одна из них длиннее другой. высота ориентировочно 25-30px. Та что покрупнее с иконкой "статистики"(график ломаной кривой к примеру) по клику на которую вывалится вниз то что сейчас поп-ап. Кнопка как бы "развернётся". Меньшая кнопка с схематическим изображением окошка. по клику на неё откроется модальное независимое окно с графиком. окно можно тягать, ресайзить и допустимо несколько таких окон. С функционалом таких модальных окошек можно развернуться.
Кейс использования модалок - отслеживание показателей датчиков с возможностью размещать на экране как удобно.

Реализация не из простых, на то и предложение )

**Comment by slavian57** [comment]
Задача частично принята в работу. В ближайшее время , ожидайте улучшения

**Comment by prohazko2** [comment]
Реализовали подобное:

![image](https://user-images.githubusercontent.com/40128245/61210235-8e436500-a704-11e9-860c-1701b7d41915.png)

![image](https://user-images.githubusercontent.com/40128245/61210131-33aa0900-a704-11e9-8600-54d1d1b67671.png)
