### ISSUE TITLE
При сохранении модели сбросилась область просмотра

### ISSUE THREAD

**Issue by maxmarvil** [Rightech/test-alpha#15]
Сохранил изменения в действиях. После сохранения форма просмотра  очистилась. Модель в левой колонке не кликабельна. 
Если переключиться на другой экран (к примеру объекта) и вернуться на модель - отобразятся старые данные (до сохранения). При перезагрузке страницы видно что данные сохранены.

![image](https://user-images.githubusercontent.com/7899443/58366281-b4087680-7ed8-11e9-8acb-7a034a20d044.png)
  + лог консоли браузера 
[sandbox.rightech.io-1558769313822.log](https://github.com/Rightech/test-alpha/files/3219202/sandbox.rightech.io-1558769313822.log)

**Comment by ferguster** [comment]
Баг исправлен, интерфейс обновлен. Большое спасибо!
