### ISSUE TITLE
Не работает смена id объекта

### ISSUE THREAD

**Issue by prohazko2** [Rightech/test-alpha#16]
При попытке сменить идентификатор объекта через страницу
https://sandbox.rightech.io/#?m=objects&p=edit 

сервер возвращает bad request.

TODO: перенести вызов процедуры смены id из интерфейса администратора в основной.

![change_id](https://user-images.githubusercontent.com/40128245/58752090-747df380-84b1-11e9-9648-a1615c66304d.gif)

**Comment by maxmarvil** [comment]
*А так можно было !? 0.0* 
Казалось что id клиента - не изменяемый id для идентификации клиентских устройств (в тех случаях когда авторизация не защищена логином паролем)
Когда заводил объект не было возможности указать авторизацию по паре логин-пароль. 

Следствие 1 : Выходит если  без "логин-пароля" соединение - то его могут использовать сторонние лица
Следствие 2 : Если с "логин-пароль", то можно id  клиента указывать произвольно(лишь бы уникально)

Всё так ?

**Comment by prohazko2** [comment]
Да, id по хорошему меняться не должен, но на практике бывают случаи когда его замена всё же требуется (без удаления объекта).

**Comment by prohazko2** [comment]
Поля с указанием логина/пароля сейчас вернули на место, при создании устройства их желательно указывать
