### ISSUE TITLE
Настройка границ влажности. Дёрганье бокса при наведении [+]

### ISSUE THREAD

**Issue by maxmarvil** [Rightech/test-alpha#2]
![image](https://user-images.githubusercontent.com/7899443/57326640-9df76980-7115-11e9-80b0-c9167f3ae484.png)

Если навести на рамку появляющуюся при сжатии бокса в кнопку [+]  то срабатывает событие out с кнопки ииии ... начинается свистопляска. Браузер хром

Натыкался на ситуацию когда плясал весь блок : появлялась прокрутка , съезжали элементы 
Повторить пока не получилось чтоб зафиксировать.

**Comment by prohazko2** [comment]
Исправили в @1.7.0-rc59
