### ISSUE TITLE
Не отображаются актуальные изменения по некоторым топикам

### ISSUE THREAD

**Issue by maxmarvil** [Rightech/test-alpha#9]
![image](https://user-images.githubusercontent.com/7899443/57566506-e8a70900-73d5-11e9-986b-97c1559d7df8.png)
![image](https://user-images.githubusercontent.com/7899443/57566543-489daf80-73d6-11e9-9f2e-3828e01afdff.png)

Приблизительно с полуночи перестали обновляться параметры влажности и RSSI 
только температура 

Устройство: 
- плата nodemcu v2 (12f)
- свежая сборная прошивка nodemcu 
- датчик bme280
- скрипт 
[init_lua.txt](https://github.com/Rightech/test-alpha/files/3168748/init_lua.txt)

если кратко - отправка прошла по всем трём топикам, для стабильности - периодичность в секунду.
если уж принт RSSI прошёл то перед ним ошибок не было
так же данные этим скриптом отправлялись ранее

**Comment by Rulur** [comment]
В платформе все отображается корректно. Последние данные по RSSI и HUM были в 23-15-58.
Как сейчас работает данный объект: Подключается - 3 секунды паузы - высылает температуру - сразу после этого отключается(через 2-3 тысяных секунды).
В тех случаях когда все данные приходили не было мгновенного разрыва соединения после их отправки.

В интерфейсе можно изменить вид отображаемых данных на json(см ниже) чтобы удобнее было смотреть что обновлялось, а что нет.
![2](https://user-images.githubusercontent.com/30890463/57568157-29aa1800-73ec-11e9-8658-7dd8cd8cc55b.png)
Топиков HUM и RSSI не было с 23-15-58

**Comment by maxmarvil** [comment]
Собственно сделал ход конём, всё прокинул одним топиком c json-формате. его субпараметры с теми же идентификаторами что и вышележащие - соответсвено (либо багово) параметры стврые приняли значения из json-объекта. 

Баг или фича? на самом деле старые параметры по старым топикам не прошли 
![image](https://user-images.githubusercontent.com/7899443/57570936-2032a700-7410-11e9-82e7-89704381d38d.png)

нет валидации идентификаторов на занятость

Пока проблемма открыта - проходит только первый топик. Устройство закрывает соединение принудительно после отправки постинга топиков. Как будто брокер не принимает последующие,
Убрал все тайминги, пытался восстановить обстановку вечера, когда топики прошли. ситуация не изменилась.

[init.txt](https://github.com/Rightech/test-alpha/files/3169109/init.txt)

**Comment by Rulur** [comment]
1) Про идентификаторы в модели: есть такая ситуация. Не уверен что это проблема, так как в теории одни и те же данные могут приходить по разным топикам. Но обдумать это стоит.
2) По логам на нашем брокере(у нас самонаписный), все выглядело так, как будто, отправив один топик, устройство тут же закрывало соединение, по TCP вылетает сообщение о закрытии соединения на стороне клиента. До 23-15, в тех случаях когда все данные доходили до платформы, не было явного закрытия соединение, и при следующей порции данных, появлялось новое соединение с тем же ID. Наш брокер закрывал старое дублирующее соединение и работал уже с новым. Я не знаком как работает mqtt в nodemcu, но может быть соединение с брокером закрывается до того как все "publish" успевают отработать?

**Comment by maxmarvil** [comment]
По 2 пункту - описанная ситуация соответсвует одному из экспериментов. В обработчике интервального таймера я оставлял коннект клиента , а закрытие вынес(по сути убрал), так как смущало постоянное открытие-закрытие сессии (не по православному как то). Далее экспериментировал с циклами внутри соединения, но не взлетело. 

в библиотеке mqtt есть ещё варианты. Попробую и их.

**Comment by maxmarvil** [comment]
Удалось стабилизировать отправку. Вероятно был рассинхрон сессии клиента и брокера ... или не рассинхрон . В общем почему проходил только первый так и остаётся загадкой. 
Стабилизировалось когда реализовал разовое подключение в рамках которого периодически публикуются топики с данными. 

Прикрепляю init.lua как рабочий образец. Работает на колбеках. Сложность была в области видимости локальных переменных внутри замыкания таймера. Не так уж и много инфы в сети по lua :-(

Может кому поможет.
[init.lua.txt](https://github.com/Rightech/test-alpha/files/3169362/init.lua.txt)
